### ISSUE TITLE
Launching spring application gives MinimumReplicasUnavailable

### ISSUE THREAD

**Issue by hect1995** [RedHat-Middleware-Workshops/dg8-workshop-labs#6]
Hi,
working in the `dg8-spring-session` exercise I am having issues when creating the `cacheapp` application.
```
$ oc get pods
NAME                        READY   STATUS             RESTARTS        AGE
cacheapp-2-build            0/1     Completed          0               11h
cacheapp-77c64d7976-q9qkr   0/1     CrashLoopBackOff   8 (4m30s ago)   20m
$ oc deployment cacheapp
...
status:
  conditions:
  - lastTransitionTime: "2021-11-09T09:15:10Z"
    lastUpdateTime: "2021-11-09T09:15:15Z"
    message: ReplicaSet "cacheapp-77c64d7976" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-09T09:36:35Z"
    lastUpdateTime: "2021-11-09T09:36:35Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

$ oc logs pod/cacheapp-77c64d7976-q9qkr
Starting the Java application using /opt/run-java/run-java.sh ...
exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -XX:+UseParallelOldGC -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/rhdg-0.0.1-SNAPSHOT.jar
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL https://10.131.0.17:8778/jolokia/

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.5.RELEASE)

2021-11-09 09:36:35.239 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225) ~[spring-beans-5.3.4.jar!/:5.3.4]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-5.3.4.jar!/:5.3.4]
	at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:588) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at com.redhat.com.rhdg.ExtRhdgApplication.main(ExtRhdgApplication.java:10) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [rhdg-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [rhdg-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [rhdg-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [rhdg-0.0.1-SNAPSHOT.jar:na]
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
	at org.springframework.context.support.AbstractApplicationContext.<init>(AbstractApplicationContext.java:228) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.context.support.GenericApplicationContext.<init>(GenericApplicationContext.java:112) ~[spring-context-5.3.4.jar!/:5.3.4]
	at org.springframework.web.context.support.GenericWebApplicationContext.<init>(GenericWebApplicationContext.java:81) ~[spring-web-5.3.4.jar!/:5.3.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.<init>(ServletWebServerApplicationContext.java:115) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext.<init>(AnnotationConfigServletWebServerApplicationContext.java:72) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_191]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212) ~[spring-beans-5.3.4.jar!/:5.3.4]
	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_191]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[rhdg-0.0.1-SNAPSHOT.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_191]
	... 24 common frames omitted
$ oc adm top nodes
NAME                                         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-10-0-128-135.eu-west-2.compute.internal   549m         7%     4678Mi          15%       
ip-10-0-139-9.eu-west-2.compute.internal     850m         24%    9452Mi          65%       
ip-10-0-178-17.eu-west-2.compute.internal    263m         3%     2558Mi          8%        
ip-10-0-183-242.eu-west-2.compute.internal   938m         26%    6976Mi          48%       
ip-10-0-198-178.eu-west-2.compute.internal   501m         6%     4214Mi          13%       
ip-10-0-212-81.eu-west-2.compute.internal    699m         19%    7366Mi          50%

**Comment by danieloh30** [comment]
How did you deploy the spring app? Did you run this command? oc new-build registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 --binary --name=cacheapp -l app=cacheapp

Which OpenShift version do you use?

**Comment by hect1995** [comment]
```
$ oc version
Client Version: 4.9.5
Server Version: 4.9.4
Kubernetes Version: v1.22.0-rc.0+ef241fd
```
```
$ mvn clean package spring-boot:repackage -f ./dg8-workshop-labs/dg8-spring-session
$ oc new-build registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 --binary --name=cacheapp -l app=cacheapp
$ oc start-build cacheapp --from-file=./dg8-workshop-labs/dg8-spring-session/target/rhdg-0.0.1-SNAPSHOT.jar --follow
$ oc new-app cacheapp && oc expose svc/cacheapp && \
oc label dc/cacheapp app.kubernetes.io/part-of=catalog app.openshift.io/runtime=spring --overwrite
```

**Comment by danieloh30** [comment]
We don't test the workshop on OCP 4.9 yet. Let me try to reproduce it on OCP 4.7 later today then will update you.

**Comment by danieloh30** [comment]
Ok. It works for me in OCP 4.7 with Spring Boot 2.2.5.RELEASE.

```
2021-11-09 16:24:29.563  WARN 1 --- [           main] org.jgroups.protocols.UDP                : JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2021-11-09 16:24:31.570  INFO 1 --- [           main] org.jgroups.protocols.pbcast.GMS         : cacheapp-5988d85456-jxgl9-64544: no members discovered after 2001 ms: creating cluster as coordinator
2021-11-09 16:24:31.579  INFO 1 --- [           main] org.infinispan.CLUSTER                   : ISPN000094: Received new cluster view for channel rhdg: [cacheapp-5988d85456-jxgl9-64544|0] (1) [cacheapp-5988d85456-jxgl9-64544]
2021-11-09 16:24:31.585  INFO 1 --- [           main] org.infinispan.CLUSTER                   : ISPN000079: Channel rhdg local address is cacheapp-5988d85456-jxgl9-64544, physical addresses are [10.128.2.55:46368]
2021-11-09 16:24:32.531  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-11-09 16:24:32.600  INFO 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
2021-11-09 16:24:32.731  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-11-09 16:24:32.734  INFO 1 --- [           main] com.redhat.com.rhdg.ExtRhdgApplication   : Started ExtRhdgApplication in 5.646 seconds (JVM running for 6.029)
```
![image](https://user-images.githubusercontent.com/14066977/140964632-035bb65c-3df8-421c-8e95-35fdbd39c57a.png)

Can you rebuild and deploy this on your cluster? If it doesn't work, retry this on OpenShift 4.7 cluster.

```
        <version.spring.boot>2.2.5.RELEASE</version.spring.boot>
        <version.spring.session>2.2.2.RELEASE</version.spring.session>
        <version.infinispan>10.1.5.Final-redhat-00001</version.infinispan>
```

**Comment by hect1995** [comment]
Thanks! Now it works except the last line: `oc label dc/cacheapp app.kubernetes.io/part-of=catalog app.openshift.io/runtime=spring --overwrite`
it tells me: `Error from server (NotFound): deploymentconfigs.apps.openshift.io "cacheapp" not found`
There is no `dc` object
```
$ oc new-app cacheapp && oc expose svc/cacheapp && \
> oc label dc/cacheapp app.kubernetes.io/part-of=catalog app.openshift.io/runtime=spring --overwrite
--> Found image ee67fa7 (About a minute old) in image stream "user-cache/cacheapp" under tag "latest" for "cacheapp"

    Java Applications 
    ----------------- 
    Platform for building and running plain Java applications (fat-jar and flat classpath)

    Tags: builder, java


--> Creating resources ...
    deployment.apps "cacheapp" created
    service "cacheapp" created
--> Success
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose service/cacheapp' 
    Run 'oc status' to view your app.
route.route.openshift.io/cacheapp exposed
Error from server (NotFound): deploymentconfigs.apps.openshift.io "cacheapp" not found

```

**Comment by hect1995** [comment]
My bad, I guess that in Openshift I need to do: `oc label deployment/cacheapp app.kubernetes.io/part-of=catalog app.openshift.io/runtime=spring --overwrite`

**Comment by danieloh30** [comment]
you're right since the app is deployed via deployment than deploymentconfig. So try to do with this:

```
oc label deployment/cacheapp app.kubernetes.io/part-of=catalog app.openshift.io/runtime=spring --overwrite
```
